Description: CFN template to create Auto Scaling Group using Launch Configuration

Resources:
  AutoScalingLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  ASLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-09a41e26df464c548
        InstanceType: t2.micro
        KeyName: vpclab-key-pair

  ASGforWali:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - us-east-1b
#      AutoScalingGroupName: Lab-6-1-2-asg
      LaunchTemplate:
        LaunchTemplateId: !Ref AutoScalingLaunchTemplate
        Version: !GetAtt AutoScalingLaunchTemplate.LatestVersionNumber
#      LaunchConfigurationName: !Ref ASGLaunchConfig
      MaxSize: 1
      MinSize: 1
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
