Description: CFN template to create Auto Scaling Group using Launch Configuration

Resources:
  ASGLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-09a41e26df464c548
      InstanceType: t2.small
      KeyName: vpclab-key-pair

  ASGforWali:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - us-east-1b
      AutoScalingGroupName: Lab-6-1-asg
      LaunchConfigurationName: !Ref ASGLaunchConfig
      MaxSize: 1
      MinSize: 1