Description: CFN template to create EC2 using Launch Template resource

Resources:
  WaliLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  WaliLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.micro
        KeyName: vpclab-key-pair
        SecurityGroupIds:
          - !GetAtt SecurityGroupUbuntu.GroupId

  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0729e439b6769d6ab
      LaunchTemplate:
        LaunchTemplateId: !Ref WaliLaunchTemplate
        Version: !GetAtt WaliLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: UbuntuInsByLT

  EIPForUbuntu:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref UbuntuInstance
      Tags:
        - Key: Name
          Value: EIPForUbuntu

  SecurityGroupUbuntu:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group to allow ssh and icmp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:  0.0.0.0/0
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0

Outputs:
  EIPUbuntu:
    Description: Output of EIP IPv4 address
    Export:
      Name: Output-EIPIPV4
    Value: !Ref EIPForUbuntu