Description: Cross-Referencing Resources within a Template using IAM user and IAM Managed policy

Parameters:
  UserName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: UserName
    Description: Please Enter the username here

Resources:
  CreateIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: Izaan@1234
        PasswordResetRequired: No

  ManagedPolicyForIAM:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: '*'
      Users:
        - !Ref CreateIAMUser