Description: This template is to create a OpenSearch Cluster

Parameters:
  MasterNodeType:
    Type: String
    AllowedValues:
      - c5.large.search
      - r5.large.search
      - t3.small.search

  DataNodeType:
    Type: String
    AllowedValues:
      - c5.large.search
      - r5.large.search
      - t3.small.search

  EBSVolumeSize:
    Type: Number

  EBSVolumeType:
    Type: String
    AllowedValues:
      - gp2
      - gp3

Resources:
  OpenSearchCluster:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: search-wali
      AdvancedSecurityOptions:
        Enabled: True
        InternalUserDatabaseEnabled: True
        MasterUserOptions:
          MasterUserName: '{{resolve:secretsmanager:OpenSearchCredential:SecretString:username}}'
          MasterUserPassword: '{{resolve:secretsmanager:OpenSearchCredential:SecretString:password}}'
      ClusterConfig:
        DedicatedMasterCount: 2
        DedicatedMasterEnabled: True
        DedicatedMasterType: !Ref MasterNodeType
        InstanceCount: 1
        InstanceType: !Ref DataNodeType

      EBSOptions:
        EBSEnabled: True
        VolumeSize: !Ref EBSVolumeSize
        VolumeType: !Ref EBSVolumeType
      DomainEndpointOptions:
        EnforceHTTPS: True
      NodeToNodeEncryptionOptions:
        Enabled: True
      EncryptionAtRestOptions:
        Enabled: True
      AccessPolicies:
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:ESHttp*'
      Tags:
        - Key: Name
          Value: Search-Wali

Outputs:
  DomainEndPoint:
    Description: This is the output of domain end point of the cluster created
    Export:
      Name: Output-DomainEndPoint-OpenSearch-Cluster
    Value: !GetAtt OpenSearchCluster.DomainEndpoint